### ISSUE TITLE
Using optionalData leads to malformed data structure on Android

### ISSUE THREAD

**Issue by felixh10r** [Catapush/catapush-react-native#1]
When sending a notification payload with `optionalData` via the backend API as per spec, the native module sends _only_ the content of `optionalData` to the JS module instead of the full `CatapushMessage`. Due to the nature of the problem, this will happen for _any_ type of nested object. The problem is that in

https://github.com/Catapush/catapush-react-native/blob/3e5143f898053b954d1286da0628526df535e6bf/android/src/main/java/com/catapush/reactnative/sdk/CatapushPluginModule.kt#L264

the `return` statement returns out of the whole `toMap` function instead of just out of `run`. The solution would be to either [label](https://kotlinlang.org/docs/returns.html#return-to-labels) the `return` statement or leave it out altogether, correctly returning `data`. 
My Kotlin is a bit rusty, but I'm happy to open a PR if desired.

Here's an example of the payload:
```json
{
  "mobileAppId": "{{AppId}}",
  "optionalData": {
    "my": "data"
  },
   ...
```

Used versions:
Kotlin 1.5.31
Gradle 7.2.1
targetSdkVersion 31

**Comment by thearaks** [comment]
Hello @felixh10r,
thank you for your bug report!

We've just released a new version of the plugin that includes this fix.

It also includes the latest major version of the Catapush Android SDK that adds the compatibility with Android 12 (API 31).

You will need to update the Android integration of your app following these 2 guides:
- [Migration from Catapush 11.1.x
](https://github.com/Catapush/catapush-docs/blob/master/AndroidSDK/DOCUMENTATION_ANDROID_SDK.md#migration-from-catapush-111x)
- [Migration from Catapush 11.2.x
](https://github.com/Catapush/catapush-docs/blob/master/AndroidSDK/DOCUMENTATION_ANDROID_SDK.md#migration-from-catapush-112x)

Regards
