### ISSUE TITLE
Bump catapush-ios-sdk-pod version

### ISSUE THREAD

**Issue by felixh10r** [Catapush/catapush-react-native#2]
[catapush_ios_sdk_pod 2.2.0](https://github.com/Catapush/catapush-ios-sdk-pod/blob/master/CHANGELOG.md#220-27092022) fixes a critical issue with iOS 16.
It would be great to be able to benefit from this fix in catapush-react-native as well 🙏

**Comment by davidemarrone** [comment]
Hi @felixh10r , tomorrow we will fix it

**Comment by thearaks** [comment]
Hi @felixh10r, 
We've just released catapush-react-native 1.3.1 on npm, check it out!
