### ISSUE TITLE
App rejected: Violation of Device and Network Abuse policy

### ISSUE THREAD

**Issue by felixh10r** [Catapush/catapush-react-native#4]
### Description

Google Play rejected my app today on grounds of their [Device and Network Abuse policy](https://support.google.com/googleplay/android-developer/answer/9888379):

> We reviewed SDKs used by your app and found noncompliant versio n(s) of SDK(s) which contains code to download executable code (for example, dex, JAR, .so files) from a source other than Google Play.

Indeed, Expo EAS Build includes `base/root/native/mac/aarch64/librobolectric-nativeruntime.dylib` in the .aab, even though it is listed as a `testImplementation`.

I don't really have an exact reason why this happens, but I pinpointed it to my upgrade of `catapush-react-native` from `1.3.1` to `1.5.0`—it's the only variable that has changed. (i.e. catapush-android-sdk:core:12.0.5 and catapush-android-sdk:gms:12.0.5)

It may be an interaction between `expo` and `catapush-react-native`, but I don't think that's normal. I can't look into the Android source of Catapush, so maybe someone on your side knows why this might happen, maybe something is misconfigured?

### Steps to Reproduce

The way this happens for me is:

`npx create-expo-app StickerSmash`

`npx expo prebuild`

`eas build --platform android`

The resulting .aab file includes the `librobolectric-nativeruntime.dylib`, because of which Google Play rejected my app update.

### Robolectric & Android Version

My dependencies include different versions of Robolectric:

4.7.3, 4.9.2, 4.10

**Comment by felixh10r** [comment]
I've also filed an issue with the library but they say there's no way it's an issue on their side: https://github.com/robolectric/robolectric/issues/8563

**Comment by davidemarrone** [comment]
Hi,
thank you for your feedback, we have released version 1.5.1 that fix this issue

regards
